'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AFASYSTEM.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AFASYS_2026_08_31_011326() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AFASYS-2026-08-31-011326", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        '''</summary>
        Friend ReadOnly Property bo_statemachine() As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = ResourceManager.GetObject("bo_statemachine", resourceCulture)
                Return CType(obj,DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        '''</summary>
        Friend ReadOnly Property book_guide_handbook_svgrepo_com() As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = ResourceManager.GetObject("book-guide-handbook-svgrepo-com", resourceCulture)
                Return CType(obj,DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property customizegrid_32x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("customizegrid_32x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        '''</summary>
        Friend ReadOnly Property education_form() As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = ResourceManager.GetObject("education-form", resourceCulture)
                Return CType(obj,DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icondunlop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icondunlop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property publicfix_32x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("publicfix_32x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        '''</summary>
        Friend ReadOnly Property signature() As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = ResourceManager.GetObject("signature", resourceCulture)
                Return CType(obj,DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property
    End Module
End Namespace
